# This is a basic workflow to help you get started with Actions

name: deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: Dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
       # 安裝 pnpm (Windows 上安裝方法)
      - name: Install pnpm
        run: |
          Invoke-WebRequest -Uri https://get.pnpm.io/install.ps1 -OutFile install.ps1
          .\install.ps1
          $env:PATH += ";C:\Users\runneradmin\AppData\Local\pnpm"
      - run: pnpm -v

      - run: pnpm install
      - run: pnpm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync build s3://${{ secrets.AWS_S3_BUCKET_NAME }}/
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
